import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
    container:{
      width:"100%",
      height:"100%"
    },
    form:{
      width:"100%",
      height:"60%",
      borderWidth:1,
      borderColor:"black",
      borderBottomEndRadius:30,
      borderBottomStartRadius:30,
      display:"flex",
      justifyContent:"center",
      alignItems:"center",
      zIndex:1
    },
    baixo:{
      height:"40%",
      width:"100%",
      display:"flex",
      alignItems:"center",
      justifyContent:"end"
    },
    textInput:{
      padding:10,
      paddingLeft:35,
      width:"80%",
      marginHorizontal:'auto',
      outlineStyle:'none',
      marginVertical:5
    },
    titulo:{
      fontWeight:"bold",
      fontSize:25
    },
    subtext:{
      fontWeight:500,
      color:'gray'
    },
    dados:{
      width:'100%',
      position:'relative'
    },  
    iconPerson:{
      position:'absolute',
      left:43,
      top:'50%',
      transform:[{translateY:-15}]
    },
    iconLock:{
      position:'absolute',
      left:40,
      top:'50%',
      transform:[{translateY:-15}]
    },
    eye:{
      position:'absolute',
      right:'17%',
      top:'50%',
      transform:[{translateY:-15}]
    },
    btnLogin:{
      padding:13,
      marginHorizontal:'auto',
      textAlign:'center',
      color:'white',
      fontWeight:500,
      fontSize:17
    },
    btnConta:{
      padding:13,
      marginHorizontal:'auto',
      textAlign:'center',
      fontWeight:500,
      fontSize:17,
      borderWidth:1.5,
      borderColor:'blue',
      borderRadius:10,
      width:'80%',
      marginTop:10
    }
  });