import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
    container:{
      flex:1,
      width:"100%",
      height:"100%"
    },
    form:{
      width:"90%",
      height:"60%",
      boxShadow:'0px 0px 15px 2px rgba(0,0,0,0.5)',
      borderRadius:20,
      zIndex:1
    },
    textInput:{
      padding:10,
      paddingLeft:35,
      width:"80%",
      marginHorizontal:'auto',
      outlineStyle:'none',
      marginVertical:5
    },
    titulo:{
      fontWeight:"bold",
      fontSize:25
    },
    subtext:{
      fontWeight:500,
      color:'gray'
    },
    dados:{
      width:'100%',
      position:'relative'
    },  
    iconPerson:{
      position:'absolute',
      left:43,
      top:'50%',
      transform:[{translateY:-15}]
    },
    iconLock:{
      position:'absolute',
      left:40,
      top:'50%',
      transform:[{translateY:-15}]
    },
    eye:{
      position:'absolute',
      right:'17%',
      top:'50%',
      transform:[{translateY:-15}]
    },
    btnLogin:{
      padding:13,
      marginHorizontal:'auto',
      textAlign:'center',
      color:'white',
      fontWeight:500,
      fontSize:17
    },
    btnConta:{
      padding:13,
      marginHorizontal:'auto',
      textAlign:'center',
      fontWeight:500,
      fontSize:16.5,
      borderWidth:1.5,
      borderColor:'blue',
      borderRadius:10,
      width:'80%',
      marginTop:10
    }
  });