import { StyleSheet } from "react-native"
export const styles=StyleSheet.create({
    container:{
        flex:1
    },
    top:{
        position:'absolute',
        top:0,
        display:'flex',
        flexDirection:'row',
        justifyContent:'space-around',
        width:'100%',
        alignItems:'center',
        height:'8%'
    },
    text:{
        fontWeight:500,
        fontSize:20
    },
    symbols:{
        fontSize:30,
        fontWeight:'bold'
    },
    clear:{
        color:'blue',
        fontWeight:500,
        fontSize:14
    },
    itens:{
        marginTop:'20%',
        marginHorizontal:'auto',
        width:'80%',
        height:'70%',
        display:'flex',
        alignItems:'center',
        justifyContent:'center',
        backgroundColor:'gray',
        borderTopStartRadius:15,
        borderTopEndRadius:15,
        borderBottomStartRadius:15,
        borderBottomEndRadius:15
    },
    item:{
        padding:10,
        width:'100%',
        borderBottomWidth:2,
        borderTopWidth:2,
        borderColor:'white'
    }
})