import {StyleSheet} from "react-native"
export const styles=StyleSheet.create({
    container:{
        backgroundColor:'white',
        display:'flex',
        flexDirection:'column',
        gap:25,
        flex:1
    },
    containerOne:{
        backgroundColor:'white',
        width:'100%',
        height:'5%',
        display:'flex',
        justifyContent:'space-between',
        flexDirection:'row',
        padding:8
    },
    containerTwo:{
        height:460,
        paddingVertical:20,
        alignItems:'center',
        overflow:'hidden'
    },
    text:{
        fontSize:23,
        fontWeight:'bold'
    },
    subtext:{
        fontSize:15,
        fontWeight:'semibold',
        color:'gray'
    },
    entrada:{
        width:'80%',
        height:50,
        fontSize:15,
        padding:5,
        backgroundColor:"#ddd",
        outlineStyle:'none',
        borderRadius:20,
        paddingLeft:15,
        marginVertical:5,
        fontWeight:500
    },
    after:{
        color:'red',
        fontSize:18,
        position:'absolute',
        right:-10,
        top:0,
        fontWeight:'bold'
    },
    search:{
        flexDirection:'row',
        width:'85%',
        height:'70%',
        backgroundColor:'#14151F',
        margin:'auto',
        borderRadius:10
    },
    btnSearch:{
        width:'50%',
        height:'100%',
        padding:5,
        borderRadius:10
    },
    titleSearch:{
        marginBottom:10
    },
    textBtnSearch:{
        fontWeight:500,
        fontSize:16,
        color:'white'
    },
    selected:{
        backgroundColor:'#211663'
    },
    list:{
        height:130,
        overflow:'hidden'
    },
    estado:{
        padding:5,
        width:150,
        backgroundColor:'#ccc',
        display:'flex',
        justifyContent:'center',
        alignItems:'center',
        height:50,
        fontWeight:700,
        fontSize:16,
        borderRadius:10,
        marginBottom:5
    },
    infoEnd:{
        display:'flex',
        alignItems:'center',
        justifyContent:'center'
    },
    estadoSelecionado:{
        backgroundColor:'#4A90E2'
    },
    label:{
        fontWeight:'bold',
        fontSize:20
    },
    btnMap:{
        padding:15,
        borderRadius:10,
        width:170,
        alignItems:'center'
    },
    textBtnMap:{
        fontWeight:600,
        fontSize:15,
        color:'white'
    }
})
