import { StyleSheet } from "react-native"
export const styles = StyleSheet.create({
    container: {
      flex: 1,
    },
    map: {
      flex: 1,
    },
    btn:{
      position:'absolute',
      width:120,
      height:50,
      elevation:5,
      right:10,
      bottom:100,
      backgroundColor:'white',
      display:'flex',
      alignItems:'center',
      justifyContent:"center",
      borderRadius:15,
      zIndex:9999
    },
    btn1:{
      position:'absolute',
      width:120,
      height:50,
      elevation:5,
      right:10,
      bottom:170,
      backgroundColor:'white',
      display:'flex',
      alignItems:'center',
      justifyContent:"center",
      borderRadius:15,
      zIndex:9999
    },
    textoBtn:{
      fontSize:15,
      fontWeight:'bold'
    },
    clima:{
        position:'absolute',
        elevation:5,
        top:10,
        right:10,
        width:120,
        height:60,
        backgroundColor:'white',
        borderRadius:10,
        display:'flex',
        alignItems:'center',
        justifyContent:'center',
        zIndex:9999
    },
    temp:{
        display:'flex',
        alignItems:'center',
        justifyContent:'center',
        textAlign:'center',
        fontWeight:800,
        fontSize:15
    },
    feedback:{
      flex:1,
      alignItems:'center',
      justifyContent:'center',
      paddingHorizontal:24,
      paddingBottom:80
    },
    feedbackTitle:{
      fontSize:22,
      fontWeight:'bold',
      color:'#1F2937',
      marginBottom:8,
      textAlign:'center'
    },
    feedbackText:{
      fontSize:15,
      color:'#475569',
      textAlign:'center',
      lineHeight:22,
      marginBottom:20
    },
    feedbackButton:{
      minWidth:160,
      height:48,
      borderRadius:12,
      backgroundColor:'#3B82F6',
      alignItems:'center',
      justifyContent:'center',
      paddingHorizontal:18
    },
    feedbackButtonText:{
      color:'white',
      fontSize:15,
      fontWeight:'bold'
    }
  })
  
