import { StyleSheet } from "react-native"
export const styles=StyleSheet.create({
    bloco1:{
      display:'flex',
      alignItems:'center',
      justifyContent:'center'
    },
    title:{
      fontWeight:500,
      fontSize:20
    },
    informations:{
      display:'flex',
      flexDirection:'row',
      alignItems:'center',
      paddingLeft:15,
      gap:10,
      paddingTop:20
    },
    photo:{
      borderRadius:100,
      height:70,
      width:70,
      borderWidth:1,
      borderColor:'black'
    },
    username:{
      fontWeight:'bold',
      fontSize:20
    },
    email:{
      color:'gray',
      fontWeight:500
    },
    itensMenu:{
      borderWidth:1,
      borderColor:'black',
      display:'flex',
      alignItems:'center',
      justifyContent:'center',
      flexDirection:'column',
      borderTopEndRadius:10,
      borderTopStartRadius:10,
      borderBottomEndRadius:10,
      borderBottomStartRadius:10,
      marginTop:10,
      marginHorizontal:10
    },
    item:{
      padding:5
    },
    linha:{
      display:'flex',
      flexDirection:'row',
      alignItems:'center',
      justifyContent:'space-around',
      width:'100%',
      padding:5
    }
  })