import { Dimensions, Platform, StyleSheet } from "react-native";
const { width } = Dimensions.get("window")
const isWeb = Platform.OS === "web"

export const styles=StyleSheet.create({
    container:{
        position:'absolute',
        top:-25,
        right:0,
        bottom:0,
        left:0,
        alignItems:'center',
        justifyContent:'center',
        paddingHorizontal:18,
        paddingVertical:28,
        zIndex:20
    },
    panel:{
        width:width > 768 ? 560 : '100%',
        maxHeight:'82%',
        backgroundColor:'#F8FBFF',
        borderRadius:24,
        borderWidth:1,
        borderColor:'#D9E8FF',
        overflow:'hidden',
        shadowColor:'#0F172A',
        shadowOffset:{
            width:0,
            height:12
        },
        shadowOpacity:0.18,
        shadowRadius:24,
        elevation:12
    },
    header:{
        minHeight:96,
        paddingHorizontal:18,
        paddingVertical:18,
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
        gap:14,
        backgroundColor:'#FFFFFF',
        borderBottomWidth:1,
        borderBottomColor:'#E4EEFF'
    },
    titleGroup:{
        flex:1,
        minWidth:0
    },
    title:{
        color:'#0F172A',
        fontSize:width > 380 ? 22 : 19,
        fontWeight:'800',
        flexShrink:1
    },
    subtitle:{
        color:'#64748B',
        fontSize:14,
        fontWeight:'600',
        marginTop:4
    },
    badge:{
        minWidth:54,
        height:34,
        borderRadius:17,
        alignItems:'center',
        justifyContent:'center',
        backgroundColor:'#EAF4FF',
        borderWidth:1,
        borderColor:'#B9DAFF',
        flexShrink:0
    },
    badgeText:{
        color:'#2563EB',
        fontSize:13,
        fontWeight:'800'
    },
    itens:{
        padding:16,
        paddingBottom:20,
        gap:12
    },
    card:{
        width:'100%',
        backgroundColor:'#ccc',
        borderRadius:18,
        padding:16,
        borderWidth:1,
        borderColor:'#DCEBFF',
        shadowColor:'#3B82F6',
        shadowOffset:{
            width:0,
            height:6
        },
        shadowOpacity:0.08,
        shadowRadius:12,
        elevation:4,
        ...(isWeb && {
            cursor:'default'
        })
    },
    cardTop:{
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
        gap:12,
        marginBottom:8
    },
    cep:{
        color:'#1D4ED8',
        fontSize:18,
        fontWeight:'800'
    },
    uf:{
        color:'#FFFFFF',
        fontSize:12,
        fontWeight:'800',
        backgroundColor:'#5AB2FF',
        paddingHorizontal:10,
        paddingVertical:5,
        borderRadius:12,
        overflow:'hidden'
    },
    street:{
        color:'#0F172A',
        fontSize:16,
        fontWeight:'800',
        lineHeight:22,
        marginBottom:14
    },
    infoGrid:{
        flexDirection:'row',
        flexWrap:'wrap',
        gap:10
    },
    infoItem:{
        minWidth:width > 420 ? '30%' : '45%',
        flexGrow:1,
        backgroundColor:'#F1F7FF',
        borderRadius:14,
        paddingHorizontal:12,
        paddingVertical:10
    },
    label:{
        color:'#64748B',
        fontSize:12,
        fontWeight:'800',
        textTransform:'uppercase'
    },
    value:{
        color:'#1E293B',
        fontSize:14,
        fontWeight:'700',
        marginTop:3
    },
    emptyBox:{
        minHeight:180,
        alignItems:'center',
        justifyContent:'center',
        paddingHorizontal:18,
        paddingVertical:28,
        backgroundColor:'#FFFFFF',
        borderRadius:18,
        borderWidth:1,
        borderColor:'#DCEBFF'
    },
    emptyTitle:{
        color:'#0F172A',
        fontSize:18,
        fontWeight:'800',
        textAlign:'center'
    },
    emptyText:{
        color:'#64748B',
        fontSize:14,
        fontWeight:'600',
        textAlign:'center',
        lineHeight:20,
        marginTop:8
    }
})
